/* XPM */
static char *letters_test[] = {
/* columns rows colors chars-per-pixel */
"18 447 2",
"  63",
"F 0",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFF        FFFFFFFFF         FFFFFFFF          FFFFFF         FFFFFFFF           FFFFFF           FFFFFFF          FFFFFF    FFFFF  FFFFFF    FFFFFFFFFFFFF    FFFFFF    FFFFFF FFFFFF    FFFFFFFFFFFF    FFFFFF  FFFFFF    FFFFF  FFFFFFF         FFFFFFF          FFFFFFFF         FFFFFFF          FFFFFFFF          FFFFFF           FFFFFF    FFFFF  FFFFFF    FFFFF  FFFFFF    FFFFFF  FFFFFF  FFFFFFF  FFFFFF   FFFFF   FFFFFF           FFFFF",
"FFFF        FFFFF FFF         FFFFFFFF          FFF FFF        FFFFFFFFF          FFF FFF          FFFFFFF          FFF FFF   FFF    FFF FFF   FFFFFFFFFFFFFF   FFF FFF   FFFF   FFF FFF   FFFFFFFFF FFF   FFFF    FFF FFF   FFF    FFFFFFF         FFFF FFF         FFFFFFFF         FFFF FFF         FFFFFFFF          FFF FFF          FFF FFF   FFF    FFF FFF   FFF    FFF FFF   FFFF    FFF FFF FFFFF    FFF FFF  FFF     FFF FFF          FFFF",
" FF          FFFF FF           FFF FF          FFFF FF          FFFF FF          FFFF FF          FFFF FF          FFFF FF    FFF    FFF FF    FFFFFFFFFFFFF    FFF FF    FFF    FFF FF    FFFFFFFFF FF    FFFF    FFF FF    FFF    FFF FF           FFF FF           FFF FF           FFF FF           FFF FF           FFF FF           FFF FF    FFF    FFF FF    FFF    FFF FF    FFFF    FFF FF   FFF     FFF FF           FFF FF           FFFF",
" F     FFFF   FFF F     FFFF   FFF F     FFFFFFFFFF       FFF    FFF       FFFFFFFFFF F     FFFFFFFFFF       FFFFFFFFFF F     FFF    FFF F     FFFFFFFFFFF      FFF       FF     FFF F     FFFFFFFFF F     FFFF    FFF F     FFF    FFF       FFFF   FFF F     FFF    FFF       FFFF   FFF F     FFFF   FFF             FFFFFF           FFFF       FFF    FFF F     FFF    FFF F     FFFF    FFF              FFF              FFFFF            FFFF",
"       FFFF   FFF       FFFF   FFF       FFFFFFFFFF       FFFF   FFF       FFFFFFFFFF       FFFFFFFFFF       FFFFFFFFFF       FFF    FFF       FFFFFFFFFFF      FFF             FFFF       FFFFFFFFF       FFFF    FFF       FFF    FFF       FFFF   FFF       FFF    FFF       FFFF   FFF       FFFF   FFF       FFFFFFFFFFFFFFF     FFFFFFF       FFF    FFF       FFF    FFF       FFFF    FFFFF           FFFFFF           FFFFFFFFFFF      FFFFF",
"              FFF              FFF       FFFFFFFFFF       FFFF   FFF             FFFF             FFFF       FFF   FFFF              FFF       FFFFFFFFFFF      FFF            FFFFF       FFFFFFFFF        FF     FFF        FF    FFF       FFFF   FFF       FFF    FFF       FFFF   FFF              FFF             FFFFFFFFF     FFFFFFF       FFF    FFF       FFF    FFF       FFFF    FFFFFF         FFFFFFFF         FFFFFFFFFFFF     FFFFFF",
"              FFF             FFFF       FFFFFFFFFF       FFFF   FFF              FFF              FFF       FFF    FFF              FFF       FFFFFFFFFFF      FFF           FFFFFF       FFFFFFFFF        FF     FFF              FFF       FFFF   FFF       FFF    FFF       FFFF   FFF             FFFF             FFFFFFFFF     FFFFFFF       FFF    FFF       FFF    FFF       FFFF    FFFFFFF       FFFFFFFFFF       FFFFFFFFFFFF     FFFFFFF",
"       FFFF   FFF             FFFF       FFFFFFFFFF       FFFF   FFF             FFFF             FFFF       FFF    FFF              FFF       FFFFF  FFFF      FFF           FFFFFF       FFFFFFFFF               FFF              FFF       FFFF   FFF       FFF    FFF       FFFF   FFF            FFFFFFF            FFFFFFFF     FFFFFFF       FFF    FFF       FFF    FFF       FFFF    FFFFFFF       FFFFFFFFFFF     FFFFFFFFFFFF     FFFFFFFF",
"       FFFF   FFF       FFFF   FFF       FFFFFFFFFF       FFFF   FFF       FFFFFFFFFF       FFFFFFFFFF       FFFF   FFF       FFF    FFF       FFF     FFF      FFF            FFFFF       FFFFFFFFF               FFF              FFF       FFFF   FFF             FFFF       FFFF   FFF            FFFFFFFFFFFFFFF    FFFFFFFF     FFFFFFF       FFF    FFF       FF     FFF               FFFFFFF       FFFFFFFFFFF     FFFFFFFFFFF     FFFFFFFFF",
"       FFFF   FFF       FFFF   FFF       FFFFFFFFFF       FFFF   FFF       FFFFFFFFFF       FFFFFFFFFF       FFFF   FFF       FFF    FFF       FFF     FFF      FFF             FFFF       FFFFFFFFF               FFF       FF     FFF       FFFF   FFF            FFFFF       FFFF   FFF             FFFFFFFFFFFFFF    FFFFFFFF     FFFFFFF       FFF    FFF             FFFF               FFFFFF         FFFFFFFFFF     FFFFFFFFFF      FFFFFFFFF",
"       FFFF   FFF       FFFF   FFF       FFFFFFFFFF       FFF    FFF       FFFFFFFFFF       FFFFFFFFFF       FFFF   FFF       FFF    FFF       FFF     FFF      FFF       FF     FFF       FFFFFFFFF       FFFF    FFF       FFF    FFF       FFFF   FFF            FFFFF       FFFF   FFF       FF     FFFFF            FFFFFFFF     FFFFFFF       FFF    FFF            FFFFF               FFFFF           FFFFFFFFF     FFFFFFFFF           FFFFF",
"       FFFF   FFF              FFF             FFFF              FFF             FFFF       FFFFFFFFFF              FFF       FFF    FFF       FFF              FFF       FFF    FFF            FFFF       FFFF    FFF       FFF    FFF              FFF       FFFFFFFFFF              FFF       FFF    FFF              FFFFFFFF     FFFFFFF              FFF           FFFFFF               FFF      FFF     FFFFFFFF     FFFFFFF              FFFF",
"       FFFF   FFF              FFFF             FFF              FFF              FFF       FFFFFFFFFFF            FFFF       FFF    FFF       FFF              FFF       FFFF   FFF             FFF       FFFF    FFF       FFF    FFFF            FFFF       FFFFFFFFFFF            FFFF       FFFF   FFF              FFFFFFFF     FFFFFFFF             FFFF         FFFFFFF        FF     FFF     FFFFF    FFFFFFFF     FFFFFFF              FFFF",
"F     FFFFFF  FFF             FFFFFF            FFFF            FFFF              FFF       FFFFFFFFFFFF          FFFFF       FFF    FFF       FFFFF           FFFF       FFFF   FFF             FFF       FFFF    FFF       FFF    FFFFFF         FFFFF       FFFFFFFFFFFF          FFFFF       FFFF   FFF             FFFFFFFFFF   FFFFFFFFFFF         FFFFFFF       FFFFFFFF       FFFF    FFF     FFFFF    FFFFFFFFF   FFFFFFFF              FFFF",
"FF    FFFFFF FFFFFF          FFFFFFFF          FFFFFF          FFFFFFF           FFFFF     FFFFFFFFFFFFFF         FFFFFFF    FFFFF  FFFFFF    FFFFFFF         FFFFFFF    FFFFFF FFFFFF          FFFFFF    FFFFFF  FFFFFF    FFFFF  FFFFFFF         FFFFFFF    FFFFFFFFFFFFFFFFF      FFFFFFF    FFFFFF FFFFFF          FFFFFFFFFFF   FFFFFFFFFFF         FFFFFFFF     FFFFFFFFFFF    FFFFFF  FFFFFF  FFFFFFF  FFFFFFFFFF   FFFFFFFFFF           FFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
};

/* XPM */

static char *A[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF        FFFF",
"FFFFF        FFF",
"F FF          FF",
"F F     FFFF   F",
"F       FFFF   F",
"F              F",
"F              F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"FF      FFFF   F",
"FFF    FFFFFF FF",
"FFFFFFFFFFFFFFFF",
};

static char *B[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF         FF",
"F FFF         FF",
"F FF           F",
"F F     FFFF   F",
"F       FFFF   F",
"F              F",
"F             FF",
"F             FF",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F              F",
"F              F",
"F             FF",
"FFF          FFF",
"FFFFFFFFFFFFFFFF",
};

static char *C[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF          F",
"FFFFF          F",
"F FF          FF",
"F F     FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F             FF",
"FF             F",
"FFF            F",
"FFFF          FF",
"FFFFFFFFFFFFFFFF",
};

static char *D[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF         FFF",
"F FFF        FFF",
"F FF          FF",
"F       FFF    F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFF    F",
"F              F",
"F              F",
"FF            FF",
"FFF          FFF",
"FFFFFFFFFFFFFFFF",
};

static char *E[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF           F",
"FFFFF          F",
"F FF          FF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F             FF",
"F              F",
"F             FF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F             FF",
"F              F",
"F              F",
"FFF           FF",
"FFFFFFFFFFFFFFFF",
};

static char *F[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF           F",
"F FFF          F",
"F FF          FF",
"F F     FFFFFFFF",
"F       FFFFFFFF",
"F             FF",
"F              F",
"F             FF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"FF     FFFFFFFFF",
"FFFFFFFFFFFFFFFF",
};

static char *G[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF          F",
"FFFFF          F",
"F FF          FF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFF   FF",
"F       FFF    F",
"F       FFF    F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F              F",
"FF            FF",
"FFF          FFF",
"FFFF         FFF",
"FFFFFFFFFFFFFFFF",
};

static char *H[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF    FFFFF  F",
"F FFF   FFF    F",
"F FF    FFF    F",
"F F     FFF    F",
"F       FFF    F",
"F              F",
"F              F",
"F              F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"FFF    FFFFF  FF",
"FFFFFFFFFFFFFFFF",
};

static char *I[] = {
/* columns rows colors chars-per-pixel */
"9 17 2",
"  45",
"F 0",
"FFFFFFFFF",
"FFFF    F",
"F FFF   F",
"F FF    F",
"F F     F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"F       F",
"FFF    FF",
"FFFFFFFFF",
};

static char *J[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFFFFFFFF    F",
"FFFFFFFFFFFF   F",
"FFFFFFFFF F    F",
"FFFFFFFFF      F",
"FFFFFFFFF      F",
"FFFFFFFFF      F",
"FFFFFFFFF      F",
"FFF  FFFF      F",
"F     FFF      F",
"F     FFF      F",
"F     FFF      F",
"F              F",
"F              F",
"FFF           FF",
"FFFF         FFF",
"FFFFFFFFFFFFFFFF",
};

static char *K[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF    FFFFFF F",
"F FFF   FFFF   F",
"F FF    FFF    F",
"F       FF     F",
"F             FF",
"F            FFF",
"F           FFFF",
"F           FFFF",
"F            FFF",
"F             FF",
"F       FF     F",
"F       FFF    F",
"F       FFFF   F",
"F       FFFF   F",
"FFF    FFFFFF FF",
"FFFFFFFFFFFFFFFF",
};

static char *L[] = {
/* columns rows colors chars-per-pixel */
"15 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFF",
"FFFF    FFFFFFF",
"F FFF   FFFFFFF",
"F FF    FFFFFFF",
"F F     FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F       FFFFFFF",
"F            FF",
"F             F",
"F             F",
"FFF          FF",
"FFFFFFFFFFFFFFF",
};

static char *M[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFF    FFFFFF  F",
" FFF   FFFF    F",
" FF    FFFF    F",
" F     FFFF    F",
"       FFFF    F",
"        FF     F",
"        FF     F",
"               F",
"               F",
"               F",
"       FFFF    F",
"       FFFF    F",
"       FFFF    F",
"       FFFF    F",
"FF    FFFFFF  FF",
"FFFFFFFFFFFFFFFF",
};

static char *N[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF    FFFFF  F",
"F FFF   FFF    F",
"F FF    FFF    F",
"F F     FFF    F",
"F       FFF    F",
"F        FF    F",
"F              F",
"F              F",
"F              F",
"F       FF     F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"FFF    FFFFF  FF",
"FFFFFFFFFFFFFFFF",
};

static char *O[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF         FF",
"FFFFF         FF",
"F FF           F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F              F",
"FF            FF",
"FFFF         FFF",
"FFFF         FFF",
"FFFFFFFFFFFFFFFF",
};

static char *P[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF          FF",
"F FFF         FF",
"F FF           F",
"F F     FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F             FF",
"F            FFF",
"F            FFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"F       FFFFFFFF",
"FFF    FFFFFFFFF",
"FFFFFFFFFFFFFFFF",
};

static char *Q[] = {
/* columns rows colors chars-per-pixel */
"16 18 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF         FF",
"FFFFF         FF",
"F FF           F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F       FFFF   F",
"F              F",
"FF            FF",
"FFF          FFF",
"FFFFFFF      FFF",
"FFFFFFFFF    FFF",
"FFFFFFFFFF   FFF",
};

static char *R[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF          FF",
"F FFF         FF",
"F FF           F",
"F F     FFFF   F",
"F       FFFF   F",
"F              F",
"F             FF",
"F            FFF",
"F            FFF",
"F             FF",
"F       FF     F",
"F       FFF    F",
"F       FFFF   F",
"F       FFFF   F",
"FFF    FFFFFF FF",
"FFFFFFFFFFFFFFFF",
};

static char *S[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFFF          F",
"FFFFF          F",
"F FF           F",
"F             FF",
"F       FFFFFFFF",
"F             FF",
"F             FF",
"FFF            F",
"FFFFFFFFFFF    F",
"FFFFFFFFFFF    F",
"FFF            F",
"F              F",
"F              F",
"F             FF",
"FFF          FFF",
"FFFFFFFFFFFFFFFF",
};

static char *T[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF           F",
"F FFF          F",
"F FF           F",
"FFF           FF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFFF   FFFFFF",
"FFFFFFF   FFFFFF",
"FFFFFFFFFFFFFFFF",
};

static char *U[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF    FFFFF  F",
"F FFF   FFF    F",
"F FF    FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F              F",
"FF             F",
"FFFF         FFF",
"FFFF         FFF",
"FFFFFFFFFFFFFFFF",
};

static char *V[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF    FFFFF  F",
"F FFF   FFF    F",
"F FF    FFF    F",
"F F     FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FFF    F",
"F       FF     F",
"F             FF",
"F            FFF",
"F           FFFF",
"FF         FFFFF",
"FFF       FFFFFF",
"FFFF     FFFFFFF",
"FFFFFFFFFFFFFFFF",
};

static char *W[] = {
/* columns rows colors chars-per-pixel */
"17 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFFF",
"FFFF    FFFFFF  F",
"F FFF   FFFF    F",
"F FF    FFFF    F",
"F F     FFFF    F",
"F       FFFF    F",
"F       FFFF    F",
"F       FFFF    F",
"F       FFFF    F",
"F               F",
"F               F",
"F               F",
"F               F",
"F        FF     F",
"F       FFFF    F",
"FFF    FFFFFF  FF",
"FFFFFFFFFFFFFFFFF",
};

static char *X[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF  FFFFFFF  F",
"F FFF FFFFF    F",
"F FF   FFF     F",
"F              F",
"FFF           FF",
"FFFF         FFF",
"FFFFF       FFFF",
"FFFFF       FFFF",
"FFFFF       FFFF",
"FFFF         FFF",
"FFF           FF",
"F      FFF     F",
"F     FFFFF    F",
"F     FFFFF    F",
"FFF  FFFFFFF  FF",
"FFFFFFFFFFFFFFFF",
};

static char *Y[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF   FFFFF   F",
"F FFF  FFF     F",
"F FF           F",
"F              F",
"FFF           FF",
"FFFF         FFF",
"FFFFF       FFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFF     FFFFF",
"FFFFFFF   FFFFFF",
"FFFFFFF   FFFFFF",
"FFFFFFFFFFFFFFFF",
};

static char *Z[] = {
/* columns rows colors chars-per-pixel */
"16 17 2",
"  45",
"F 0",
"FFFFFFFFFFFFFFFF",
"FFFF           F",
"F FFF          F",
"F FF           F",
"FFF            F",
"FFFFFFFF      FF",
"FFFFFFFF     FFF",
"FFFFFFF     FFFF",
"FFFFFF     FFFFF",
"FFFFF     FFFFFF",
"FFFF      FFFFFF",
"FFF           FF",
"F              F",
"F              F",
"F              F",
"FFF           FF",
"FFFFFFFFFFFFFFFF",
};


static char** letters[26] = {A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z};





